export interface Icd10Code {
  code: string;
  description: string;
  category: string;
}

export const ICD10_CODES: Icd10Code[] = [
  // ── Autism Spectrum ───────────────────────────────────────────────────────
  { code: "F84.0",  description: "Autism Spectrum Disorder",                               category: "Autism Spectrum" },
  { code: "F84.5",  description: "Asperger Syndrome",                                      category: "Autism Spectrum" },
  { code: "F84.8",  description: "Other Pervasive Developmental Disorders",                category: "Autism Spectrum" },
  { code: "F84.9",  description: "Pervasive Developmental Disorder, Unspecified",          category: "Autism Spectrum" },
  // ── ADHD ─────────────────────────────────────────────────────────────────
  { code: "F90.0",  description: "ADHD — Predominantly Inattentive",                       category: "ADHD" },
  { code: "F90.1",  description: "ADHD — Predominantly Hyperactive-Impulsive",             category: "ADHD" },
  { code: "F90.2",  description: "ADHD — Combined Presentation",                           category: "ADHD" },
  { code: "F90.8",  description: "Other ADHD",                                             category: "ADHD" },
  { code: "F90.9",  description: "ADHD, Unspecified",                                      category: "ADHD" },
  // ── Motor / Developmental Coordination ───────────────────────────────────
  { code: "F82",    description: "Specific Developmental Disorder of Motor Function (DCD/Dyspraxia)", category: "Motor / Coordination" },
  { code: "R27.0",  description: "Ataxia, Unspecified",                                   category: "Motor / Coordination" },
  { code: "R27.8",  description: "Other Lack of Coordination",                            category: "Motor / Coordination" },
  { code: "R27.9",  description: "Unspecified Lack of Coordination",                      category: "Motor / Coordination" },
  { code: "M62.81", description: "Muscle Weakness (Generalized)",                         category: "Motor / Coordination" },
  { code: "R29.3",  description: "Abnormal Posture",                                      category: "Motor / Coordination" },
  // ── Cerebral Palsy ────────────────────────────────────────────────────────
  { code: "G80.0",  description: "Spastic Quadriplegic Cerebral Palsy",                   category: "Cerebral Palsy" },
  { code: "G80.1",  description: "Spastic Diplegic Cerebral Palsy",                      category: "Cerebral Palsy" },
  { code: "G80.2",  description: "Spastic Hemiplegic Cerebral Palsy",                    category: "Cerebral Palsy" },
  { code: "G80.3",  description: "Athetoid Cerebral Palsy",                              category: "Cerebral Palsy" },
  { code: "G80.4",  description: "Ataxic Cerebral Palsy",                                category: "Cerebral Palsy" },
  { code: "G80.8",  description: "Other Cerebral Palsy",                                 category: "Cerebral Palsy" },
  { code: "G80.9",  description: "Cerebral Palsy, Unspecified",                          category: "Cerebral Palsy" },
  // ── Language / Communication ──────────────────────────────────────────────
  { code: "F80.0",  description: "Phonological Disorder",                                 category: "Language / Communication" },
  { code: "F80.1",  description: "Expressive Language Disorder",                         category: "Language / Communication" },
  { code: "F80.2",  description: "Mixed Receptive-Expressive Language Disorder",         category: "Language / Communication" },
  { code: "F80.4",  description: "Speech Delay Due to Hearing Loss",                     category: "Language / Communication" },
  { code: "F80.81", description: "Childhood Onset Fluency Disorder (Stuttering)",        category: "Language / Communication" },
  { code: "F80.82", description: "Social Pragmatic Communication Disorder",              category: "Language / Communication" },
  { code: "F80.89", description: "Other Developmental Disorders of Speech / Language",   category: "Language / Communication" },
  { code: "F80.9",  description: "Developmental Disorder of Speech / Language, Unspecified", category: "Language / Communication" },
  // ── Learning Disorders ────────────────────────────────────────────────────
  { code: "F81.0",  description: "Specific Reading Disorder (Dyslexia)",                 category: "Learning Disorders" },
  { code: "F81.2",  description: "Mathematics Disorder (Dyscalculia)",                   category: "Learning Disorders" },
  { code: "F81.81", description: "Disorder of Written Expression (Dysgraphia)",          category: "Learning Disorders" },
  { code: "F81.89", description: "Other Developmental Disorders of Scholastic Skills",   category: "Learning Disorders" },
  { code: "F81.9",  description: "Developmental Disorder of Scholastic Skills, Unspecified", category: "Learning Disorders" },
  // ── Intellectual Disabilities ─────────────────────────────────────────────
  { code: "F70",    description: "Mild Intellectual Disability",                          category: "Intellectual Disabilities" },
  { code: "F71",    description: "Moderate Intellectual Disability",                      category: "Intellectual Disabilities" },
  { code: "F72",    description: "Severe Intellectual Disability",                        category: "Intellectual Disabilities" },
  { code: "F73",    description: "Profound Intellectual Disability",                      category: "Intellectual Disabilities" },
  { code: "F78.A1", description: "SYNGAP1-Related Intellectual Disability",               category: "Intellectual Disabilities" },
  { code: "F79",    description: "Unspecified Intellectual Disability",                   category: "Intellectual Disabilities" },
  // ── Down Syndrome ─────────────────────────────────────────────────────────
  { code: "Q90.0",  description: "Trisomy 21, Nonmosaicism (Down Syndrome)",              category: "Chromosomal / Genetic" },
  { code: "Q90.1",  description: "Trisomy 21, Mosaicism",                                 category: "Chromosomal / Genetic" },
  { code: "Q90.9",  description: "Down Syndrome, Unspecified",                            category: "Chromosomal / Genetic" },
  { code: "Q96.9",  description: "Turner Syndrome, Unspecified",                          category: "Chromosomal / Genetic" },
  { code: "Q93.51", description: "Angelman Syndrome",                                     category: "Chromosomal / Genetic" },
  { code: "Q93.81", description: "Velo-Cardio-Facial Syndrome (22q11.2 deletion)",        category: "Chromosomal / Genetic" },
  { code: "Q93.89", description: "Other Deletions from Autosomes",                        category: "Chromosomal / Genetic" },
  { code: "Q92.8",  description: "Other Specified Trisomies / Partial Trisomies",         category: "Chromosomal / Genetic" },
  // ── Other Genetic Syndromes ───────────────────────────────────────────────
  { code: "Q87.11", description: "Prader-Willi Syndrome",                                 category: "Chromosomal / Genetic" },
  { code: "Q87.19", description: "Other Congenital Malformation Syndromes with Short Stature", category: "Chromosomal / Genetic" },
  { code: "Q85.00", description: "Neurofibromatosis (NF1)",                               category: "Chromosomal / Genetic" },
  { code: "Q89.8",  description: "Other Specified Congenital Malformations (Fragile X)",  category: "Chromosomal / Genetic" },
  // ── Sensory Processing ────────────────────────────────────────────────────
  { code: "F88",    description: "Other Disorders of Psychological Development (Sensory Processing)", category: "Sensory Processing" },
  { code: "H90.3",  description: "Sensorineural Hearing Loss, Bilateral",                 category: "Sensory Processing" },
  { code: "H90.6",  description: "Mixed Conductive and Sensorineural Hearing Loss, Bilateral", category: "Sensory Processing" },
  { code: "H53.10", description: "Unspecified Visual Disturbance",                        category: "Sensory Processing" },
  { code: "H50.00", description: "Unspecified Esotropia",                                 category: "Sensory Processing" },
  { code: "H50.30", description: "Unspecified Intermittent Heterotropia",                 category: "Sensory Processing" },
  // ── Feeding / Eating ──────────────────────────────────────────────────────
  { code: "F50.82", description: "Avoidant / Restrictive Food Intake Disorder (ARFID)",  category: "Feeding / Eating" },
  { code: "F98.29", description: "Other Feeding Disorders of Infancy and Early Childhood", category: "Feeding / Eating" },
  { code: "R63.3",  description: "Feeding Difficulties",                                  category: "Feeding / Eating" },
  { code: "P92.01", description: "Hypersensitive Latching — Breastfeeding",               category: "Feeding / Eating" },
  // ── Anxiety / Behavioral ──────────────────────────────────────────────────
  { code: "F41.9",  description: "Anxiety Disorder, Unspecified",                         category: "Behavioral / Emotional" },
  { code: "F93.0",  description: "Separation Anxiety Disorder of Childhood",              category: "Behavioral / Emotional" },
  { code: "F94.0",  description: "Selective Mutism",                                      category: "Behavioral / Emotional" },
  { code: "F91.0",  description: "Conduct Disorder, Childhood-Onset",                    category: "Behavioral / Emotional" },
  { code: "F91.3",  description: "Oppositional Defiant Disorder",                         category: "Behavioral / Emotional" },
  { code: "F98.4",  description: "Stereotyped Movement Disorders",                        category: "Behavioral / Emotional" },
  { code: "F94.8",  description: "Other Childhood Disorders of Social Functioning",       category: "Behavioral / Emotional" },
  // ── Premature / NICU ──────────────────────────────────────────────────────
  { code: "P07.10", description: "Other Low Birth Weight Newborn",                        category: "Birth / Premature" },
  { code: "P07.20", description: "Extreme Immaturity of Newborn (< 28 weeks)",            category: "Birth / Premature" },
  { code: "P07.30", description: "Preterm Newborn (28–31 weeks)",                         category: "Birth / Premature" },
  { code: "P07.38", description: "Preterm Newborn (34–36 weeks)",                         category: "Birth / Premature" },
  { code: "P91.60", description: "Hypoxic-Ischemic Encephalopathy (HIE), Unspecified",   category: "Birth / Premature" },
  { code: "P11.0",  description: "Cerebral Edema Due to Birth Injury",                    category: "Birth / Premature" },
  // ── Muscular / Neurological ───────────────────────────────────────────────
  { code: "G71.00", description: "Muscular Dystrophy, Unspecified",                       category: "Muscular / Neurological" },
  { code: "G71.01", description: "Duchenne Muscular Dystrophy",                           category: "Muscular / Neurological" },
  { code: "G71.02", description: "Facioscapulohumeral Muscular Dystrophy",                category: "Muscular / Neurological" },
  { code: "G12.0",  description: "Infantile Spinal Muscular Atrophy (SMA)",               category: "Muscular / Neurological" },
  { code: "G12.1",  description: "Other Inherited Spinal Muscular Atrophy",               category: "Muscular / Neurological" },
  { code: "G35",    description: "Multiple Sclerosis",                                    category: "Muscular / Neurological" },
  { code: "G43.909",description: "Migraine, Unspecified",                                 category: "Muscular / Neurological" },
  { code: "G89.29", description: "Other Chronic Pain",                                    category: "Muscular / Neurological" },
  // ── Traumatic Brain Injury / Stroke ───────────────────────────────────────
  { code: "S06.0X0A",description: "Concussion without Loss of Consciousness — Initial",  category: "Trauma / Acquired" },
  { code: "S06.0X9A",description: "Concussion with LOC, Unspecified Duration — Initial", category: "Trauma / Acquired" },
  { code: "S09.90XA",description: "Unspecified Injury of Head — Initial",                category: "Trauma / Acquired" },
  { code: "I69.351", description: "Hemiplegia Following Cerebral Infarction",             category: "Trauma / Acquired" },
  { code: "I69.391", description: "Dysphagia Following Cerebral Infarction",              category: "Trauma / Acquired" },
  // ── Hand / Upper Extremity ────────────────────────────────────────────────
  { code: "M79.622",description: "Pain in Left Upper Arm",                                category: "Hand / Upper Extremity" },
  { code: "M79.621",description: "Pain in Right Upper Arm",                               category: "Hand / Upper Extremity" },
  { code: "G54.2",  description: "Cervical Root Disorders",                               category: "Hand / Upper Extremity" },
  { code: "M65.011",description: "De Quervain's Tenosynovitis, Right Wrist",              category: "Hand / Upper Extremity" },
  { code: "M65.012",description: "De Quervain's Tenosynovitis, Left Wrist",              category: "Hand / Upper Extremity" },
  { code: "G56.00", description: "Carpal Tunnel Syndrome, Unspecified Upper Limb",       category: "Hand / Upper Extremity" },
  { code: "G56.01", description: "Carpal Tunnel Syndrome, Right Upper Limb",             category: "Hand / Upper Extremity" },
  { code: "G56.02", description: "Carpal Tunnel Syndrome, Left Upper Limb",              category: "Hand / Upper Extremity" },
  { code: "M72.0",  description: "Palmar Fascial Fibromatosis (Dupuytren's)",             category: "Hand / Upper Extremity" },
  { code: "S62.001A",description: "Fracture of Scaphoid — Initial",                      category: "Hand / Upper Extremity" },
  // ── Spinal Cord / Orthopedic ──────────────────────────────────────────────
  { code: "M54.50", description: "Low Back Pain, Unspecified",                            category: "Orthopedic / Spine" },
  { code: "M54.2",  description: "Cervicalgia (Neck Pain)",                               category: "Orthopedic / Spine" },
  { code: "M54.12", description: "Radiculopathy, Cervical Region",                        category: "Orthopedic / Spine" },
  { code: "S14.109A",description: "Unspecified Injury of Cervical Spinal Cord — Initial",category: "Orthopedic / Spine" },
  { code: "S24.109A",description: "Unspecified Injury of Thoracic Spinal Cord — Initial",category: "Orthopedic / Spine" },
  { code: "S34.109A",description: "Unspecified Injury of Lumbar Spinal Cord — Initial",  category: "Orthopedic / Spine" },
  // ── Delayed Development (General) ────────────────────────────────────────
  { code: "F89",    description: "Unspecified Disorder of Psychological Development",     category: "Developmental Delay" },
  { code: "F88",    description: "Other Disorders of Psychological Development",          category: "Developmental Delay" },
  { code: "R62.50", description: "Unspecified Lack of Expected Normal Physiological Development", category: "Developmental Delay" },
  { code: "R62.0",  description: "Delayed Milestone in Childhood",                        category: "Developmental Delay" },
  { code: "Z13.42", description: "Encounter for Screening for Global Developmental Delays", category: "Developmental Delay" },
  // ── Rett Syndrome / Other ─────────────────────────────────────────────────
  { code: "F84.2",  description: "Rett Syndrome",                                         category: "Other Neurological" },
  { code: "F84.3",  description: "Other Childhood Disintegrative Disorder",               category: "Other Neurological" },
  { code: "G40.909",description: "Epilepsy, Unspecified",                                 category: "Other Neurological" },
  { code: "G40.501",description: "Lennox-Gastaut Syndrome",                               category: "Other Neurological" },
  { code: "G47.00", description: "Insomnia, Unspecified",                                 category: "Other Neurological" },
  { code: "R41.3",  description: "Other Amnesia",                                         category: "Other Neurological" },
  { code: "R48.8",  description: "Other Symbolic Dysfunctions (Visual-Perceptual)",       category: "Other Neurological" },
];
